AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/**'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
