default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  username: 'username'
  password: 'password'

development:
  <<: *default
  database: 'ror_challenge_development'

test:
  <<: *default
  database: 'ror_challenge_test'
